openapi: "3.0.0"
info:
  title: A plain text API description? WHAT!
  version: 0.0.1
servers:
  - url: https://emancipated-badger.io
components:
  schemas:
    Hike:
      type: object
      properties:
        size:
          type: integer
          format: int32
        make:
          type: string
    Bike:
      type: object
      properties:
        id:
          type: integer
          format: int64
        model:
          type: string
        age:
          type: integer
paths:
  /bikes:
      get:
        summary: list all bikes
        operationId: getBikes
        tags:
            - bikes
        parameters:
            - name: make
              in: query
              description: Bike make?
        responses:
          '200':
            description: A list of pets.
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/pet'
  /hikes:
      get:
        summary: list all hikes
        operationId: getHikes
        tags:
            - hikes
        parameters:
            - name: make
              in: query
              description: Shoe make?
        response:
            '200':
              description: ALL the hike stuff
      post:
        summary: create a listing
        operationId: postHike
        tags:
            - hikes
        parameters:
            - name: hike
              in: body
              description: Hike stuff
        response:
            '200':
              description: ALL the hike stuff