version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: chiaseeds
      POSTGRES_USER: organic_almond_milk
      POSTGRES_DB: bikehike
    ports:
      - 7000:5432
